name: GitHub Readme Stats
on:
  workflow_dispatch:
  schedule:
  - cron: 0 */12 * * *  
jobs:
  update-cards:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: Update cards
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure output folder
        run: mkdir -p profile

      - name: Generate stats (dark mode)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: 'username=${{ github.repository_owner }}&show_icons=true&line_height=28&hide_border=true&card_width=347&include_all_commits=true&role=owner,collaborator&show=reviews,discussions_answered&hide_rank=true&exclude_repo=github-readme-stats&theme=github_dark&bg_color=000000'
          path: profile/stats-dark.svg
          token: ${{ secrets.PAT }}

      - name: Generate top languages (dark mode)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: 'username=${{ github.repository_owner }}&layout=compact&langs_count=12&hide_border=true&role=owner,collaborator&theme=github_dark&bg_color=000000'
          path: profile/top-langs-dark.svg
          token: ${{ secrets.PAT }}

      - name: Commit cards
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push